services:
  postgres:
    build:
      context: ./pg_vector   # Path to the directory containing the Dockerfile
      dockerfile: pg_vector.Dockerfile
    ports:
      - "5432:5432"
    volumes:
      - ./pg_vector/data:/var/lib/postgresql/data
      - ./pg_vector/init_pgvector.sql:/docker-entrypoint-initdb.d/init_pgvector.sql
    environment:
      POSTGRES_USER: my_pg_user
      POSTGRES_PASSWORD: pg_vector
      POSTGRES_DB: vector_db
